name: C/C++ CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential \
                                libsdl2-dev \
                                libsdl2-image-dev \
                                libsdl2-ttf-dev

    - name: Verify SDL2 installation
      run: |
        dpkg -L libsdl2-dev

    - name: Build with make
      run: |
        make
